// Metro area definitions for city pages
// Maps metro slugs to arrays of cities that should be included

export interface MetroArea {
  displayName: string
  state: string
  cities: string[]
  description: string
}

export const metroAreas: Record<string, MetroArea> = {
  "los-angeles": {
    displayName: "Los Angeles Area",
    state: "CA",
    cities: [
      "Los Angeles",
      "Hollywood",
      "West Hollywood",
      "Beverly Hills",
      "Santa Monica",
      "Culver City",
      "Venice",
      "Westwood",
      "Century City",
      "West Los Angeles",
      "Marina del Rey",
      "Glendale",
      "Burbank",
      "Pasadena",
      "North Hollywood",
      "Sherman Oaks",
      "Encino",
      "Van Nuys",
      "Studio City",
      "Woodland Hills",
      "Long Beach",
      "Torrance",
      "Redondo Beach",
      "Hermosa Beach",
      "Manhattan Beach",
      "El Segundo",
      "Gardena",
      "Inglewood",
      "Hawthorne",
      "Downey",
      "Whittier",
      "Alhambra",
      "Arcadia",
      "Monrovia",
      "Claremont",
      "Pomona",
      "Anaheim",
      "Irvine",
      "Costa Mesa",
      "Newport Beach",
      "Santa Ana",
      "Fullerton",
      "Orange",
      "Huntington Beach",
    ],
    description: "Discover independent and art house cinemas across the Los Angeles metro area. From historic Hollywood theaters to beachside venues in Santa Monica, find the best repertory and indie film venues in Southern California.",
  },

  "new-york": {
    displayName: "New York Area",
    state: "NY",
    cities: [
      "New York",
      "Manhattan",
      "Brooklyn",
      "Queens",
      "Bronx",
      "Staten Island",
      "Hoboken",
      "Jersey City",
      "Newark",
      "Yonkers",
      "White Plains",
      "New Rochelle",
      "Mount Vernon",
      "Astoria",
      "Long Island City",
      "Flushing",
      "Jamaica",
      "Forest Hills",
      "Ridgewood",
      "Williamsburg",
      "Greenpoint",
      "Park Slope",
      "Fort Greene",
      "DUMBO",
      "Cobble Hill",
      "Carroll Gardens",
      "Red Hook",
      "Prospect Heights",
      "Crown Heights",
      "Bed-Stuy",
      "Bushwick",
    ],
    description: "Explore New York City's legendary art house theater scene. From Manhattan's Film Forum to Brooklyn's indie havens, find independent cinemas showing classic and contemporary films across the five boroughs and beyond.",
  },

  "san-francisco": {
    displayName: "San Francisco Bay Area",
    state: "CA",
    cities: [
      "San Francisco",
      "Oakland",
      "Berkeley",
      "Emeryville",
      "Alameda",
      "Richmond",
      "San Rafael",
      "Sausalito",
      "Mill Valley",
      "Tiburon",
      "Larkspur",
      "Corte Madera",
      "Novato",
      "Palo Alto",
      "Mountain View",
      "Menlo Park",
      "Redwood City",
      "San Mateo",
      "Burlingame",
      "South San Francisco",
      "Daly City",
      "San Jose",
      "Santa Clara",
      "Sunnyvale",
      "Cupertino",
      "Fremont",
      "Hayward",
      "Walnut Creek",
      "Concord",
      "Pleasant Hill",
      "Lafayette",
      "Orinda",
    ],
    description: "Discover art house cinemas across the San Francisco Bay Area. From historic theaters in the city to East Bay gems in Oakland and Berkeley, find independent film venues throughout Northern California.",
  },

  "chicago": {
    displayName: "Chicago Area",
    state: "IL",
    cities: [
      "Chicago",
      "Evanston",
      "Oak Park",
      "Skokie",
      "Wilmette",
      "Winnetka",
      "Highland Park",
      "Lake Forest",
      "Naperville",
      "Aurora",
      "Schaumburg",
      "Des Plaines",
      "Arlington Heights",
      "Cicero",
      "Berwyn",
      "Park Ridge",
      "Elmhurst",
      "Downers Grove",
      "Glen Ellyn",
      "Wheaton",
    ],
    description: "Discover Chicago's independent cinema landscape. Find art house theaters, repertory houses, and community cinemas throughout the Windy City and its surrounding suburbs.",
  },

  "boston": {
    displayName: "Boston Area",
    state: "MA",
    cities: [
      "Boston",
      "Cambridge",
      "Somerville",
      "Brookline",
      "Newton",
      "Watertown",
      "Arlington",
      "Medford",
      "Malden",
      "Quincy",
      "Dedham",
      "Waltham",
      "Lexington",
      "Concord",
      "Salem",
      "Beverly",
      "Gloucester",
      "Northampton",
      "Amherst",
    ],
    description: "Explore Boston's vibrant art house theater scene. From Harvard Square's historic cinemas to indie venues throughout Greater Boston, find independent film venues in New England's cultural hub.",
  },

  "philadelphia": {
    displayName: "Philadelphia Area",
    state: "PA",
    cities: [
      "Philadelphia",
      "Camden",
      "Ardmore",
      "Bryn Mawr",
      "Media",
      "Doylestown",
      "Ambler",
      "Jenkintown",
      "Narberth",
      "Bala Cynwyd",
      "Wayne",
      "Haverford",
      "Wilmington",
    ],
    description: "Find art house theaters in Philadelphia and the surrounding region. Discover independent cinemas, repertory houses, and historic venues across the Delaware Valley.",
  },

  "washington-dc": {
    displayName: "Washington DC Area",
    state: "DC",
    cities: [
      "Washington",
      "Arlington",
      "Alexandria",
      "Bethesda",
      "Silver Spring",
      "Rockville",
      "Chevy Chase",
      "Takoma Park",
      "College Park",
      "Falls Church",
      "Fairfax",
      "McLean",
      "Vienna",
      "Reston",
      "Tysons",
    ],
    description: "Discover art house cinemas in the nation's capital and surrounding areas. Find independent theaters and repertory houses across DC, Maryland, and Northern Virginia.",
  },

  "seattle": {
    displayName: "Seattle Area",
    state: "WA",
    cities: [
      "Seattle",
      "Bellevue",
      "Tacoma",
      "Redmond",
      "Kirkland",
      "Renton",
      "Everett",
      "Edmonds",
      "Bainbridge Island",
      "Burien",
      "Federal Way",
      "Olympia",
    ],
    description: "Find art house theaters in Seattle and the Puget Sound region. Discover independent cinemas, film festivals, and community venues in the Pacific Northwest.",
  },

  "dallas": {
    displayName: "Dallas-Fort Worth Area",
    state: "TX",
    cities: [
      "Dallas",
      "Fort Worth",
      "Arlington",
      "Plano",
      "Irving",
      "Frisco",
      "Richardson",
      "Garland",
      "McKinney",
      "Denton",
      "Carrollton",
      "Lewisville",
      "Grand Prairie",
      "Mesquite",
    ],
    description: "Explore the Dallas-Fort Worth metroplex's art house theater scene. Find independent cinemas and repertory houses across North Texas.",
  },

  "houston": {
    displayName: "Houston Area",
    state: "TX",
    cities: [
      "Houston",
      "Sugar Land",
      "The Woodlands",
      "Pasadena",
      "Pearland",
      "League City",
      "Katy",
      "Baytown",
      "Conroe",
      "Missouri City",
      "Galveston",
    ],
    description: "Discover art house theaters in Houston and the surrounding Gulf Coast region. Find independent cinemas and repertory venues across America's fourth-largest city.",
  },

  "miami": {
    displayName: "Miami Area",
    state: "FL",
    cities: [
      "Miami",
      "Miami Beach",
      "Fort Lauderdale",
      "Coral Gables",
      "Coconut Grove",
      "Hollywood",
      "Boca Raton",
      "Delray Beach",
      "West Palm Beach",
      "Palm Beach",
      "Pompano Beach",
      "Deerfield Beach",
      "Hialeah",
      "Aventura",
      "Key Biscayne",
    ],
    description: "Find art house theaters across South Florida. From Miami Beach's iconic venues to Fort Lauderdale's indie cinemas, discover independent film culture in the Sunshine State.",
  },

  "denver": {
    displayName: "Denver Area",
    state: "CO",
    cities: [
      "Denver",
      "Boulder",
      "Aurora",
      "Lakewood",
      "Littleton",
      "Englewood",
      "Arvada",
      "Westminster",
      "Thornton",
      "Centennial",
      "Golden",
      "Broomfield",
      "Fort Collins",
    ],
    description: "Discover art house theaters in Denver and the Front Range. Find independent cinemas and repertory houses across Colorado's Mile High City and beyond.",
  },

  "portland": {
    displayName: "Portland Area",
    state: "OR",
    cities: [
      "Portland",
      "Beaverton",
      "Lake Oswego",
      "Tigard",
      "Hillsboro",
      "Gresham",
      "Milwaukie",
      "Oregon City",
      "West Linn",
      "Vancouver",
    ],
    description: "Explore Portland's unique art house theater scene. Find indie cinemas, brewpub theaters, and repertory houses in Oregon's creative capital and beyond.",
  },

  "detroit": {
    displayName: "Detroit Area",
    state: "MI",
    cities: [
      "Detroit",
      "Ann Arbor",
      "Dearborn",
      "Royal Oak",
      "Ferndale",
      "Birmingham",
      "Bloomfield Hills",
      "Troy",
      "Southfield",
      "Warren",
      "Grosse Pointe",
      "Ypsilanti",
    ],
    description: "Find art house theaters in Detroit and Southeast Michigan. Discover independent cinemas and repertory houses from downtown Detroit to Ann Arbor's vibrant film scene.",
  },

  "minneapolis": {
    displayName: "Minneapolis-St. Paul Area",
    state: "MN",
    cities: [
      "Minneapolis",
      "St. Paul",
      "Saint Paul",
      "Bloomington",
      "Eden Prairie",
      "Minnetonka",
      "Edina",
      "St. Louis Park",
      "Hopkins",
      "Richfield",
      "Roseville",
      "Maplewood",
    ],
    description: "Discover art house cinemas in the Twin Cities. Find independent theaters and repertory houses across Minneapolis, St. Paul, and the surrounding metro area.",
  },

  "atlanta": {
    displayName: "Atlanta Area",
    state: "GA",
    cities: [
      "Atlanta",
      "Decatur",
      "Marietta",
      "Sandy Springs",
      "Alpharetta",
      "Roswell",
      "Smyrna",
      "Dunwoody",
      "Buckhead",
      "Midtown",
      "East Point",
      "College Park",
    ],
    description: "Explore Atlanta's art house theater scene. Find independent cinemas and repertory houses throughout Georgia's capital city and its surrounding communities.",
  },

  "austin": {
    displayName: "Austin Area",
    state: "TX",
    cities: [
      "Austin",
      "Round Rock",
      "Cedar Park",
      "Pflugerville",
      "Georgetown",
      "San Marcos",
      "Kyle",
      "Buda",
      "Lakeway",
      "Dripping Springs",
    ],
    description: "Explore Austin's vibrant art house theater scene. From the Alamo Drafthouse to historic venues, find indie cinemas in Texas's film-loving capital and surrounding Hill Country.",
  },
}

// Helper to check if a slug is a metro area
export function isMetroArea(slug: string): boolean {
  return slug in metroAreas
}

// Get metro area config or null
export function getMetroArea(slug: string): MetroArea | null {
  return metroAreas[slug] || null
}

// Convert city names to lowercase for case-insensitive matching
export function getMetroCitiesLower(slug: string): string[] {
  const metro = metroAreas[slug]
  if (!metro) return []
  return metro.cities.map(city => city.toLowerCase())
}
